version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: auto_spa_db
      POSTGRES_USER: auto_spa_user
      POSTGRES_PASSWORD: auto_spa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auto_spa_user -d auto_spa_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://auto_spa_user:auto_spa_password@db:5432/auto_spa_db
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: